### ISSUE TITLE
[BUG]: Apple Pay icon disappears on `<PaymentElement>`

### ISSUE THREAD

**Issue by MoistCode** [stripe/react-stripe-js#299] opened 2022-06-03 14:17 UTC
## What happened?
While working with the `<PaymentElement>`, my team noticed that the Apple Pay icon disappeared after selecting "Apple Pay " then selecting "Cards". A video demonstrating the issue seen can be found in the link below:

https://share.getcloudapp.com/BluGpAEO

## How to reproduce
1. Navigate to https://stripe.com/docs/payments/payment-element on a device that supports and has Apple Pay configured.
2. Click on the "Apple Pay" tab.
3. Click on the "Cards" tab.

### Environment

Safari 15.5 on macOS Monterey 12.4

### Reproduction

https://stripe.com/docs/payments/payment-element

**Comment by tylersmith-stripe** [comment] 2022-06-03 14:49
Thank you for reporting, @MoistCode! I can confirm that this issue reproduces consistently on Safari. We'll investigate a solution and update this thread.

**Comment by tylersmith-stripe** [comment] 2022-06-03 16:37
We've identified the root cause of this issue and a fix has been merged in! This fix will be deployed soon (~a few hours).

cc @MoistCode

**Comment by tylersmith-stripe** [comment] 2022-06-03 22:12
This fix has been deployed, and can be verified at the URL you shared. Thank you again for reporting this issue to us!

**Closed by tylersmith-stripe** 2022-06-03 22:12 UTC
Labels: bug
