### ISSUE TITLE
[BUG]: IntegrationError loaderUi Element didn't mount normally.

### ISSUE THREAD

**Issue by m-nathani** [stripe/react-stripe-js#371] opened 2023-01-06 08:40 UTC
### What happened?

While using stripe checkout, we found a unexpected error on:

```
    "@stripe/react-stripe-js": "^1.6.0",
    "@stripe/stripe-js": "^1.19.1",
```

Here is the public details for the error:
https://sentry.io/share/issue/c98c0faf67194c2d8c7ddcd0a483e684/

### Environment

Chrome 108.0.5359.124

### Reproduction

https://letsumai.com/widget/zen-by-mel

**Comment by christopher-stripe** [comment] 2023-01-13 17:27
Closing as duplicate of https://github.com/stripe/stripe-js/issues/408

**Closed by christopher-stripe** 2023-01-13 17:27 UTC
Labels: bug
